import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import Hero from "@/components/Hero";
import Bio from "@/components/Bio";
import Features from "@/components/Features";
import Process from "@/components/Process";
import Industries from "@/components/Industries";
import Agencies from "@/components/Agencies";
import Services from "@/components/Services";
import Models from "@/components/Models";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main className={`${styles.main} ${inter.className}`}>
				<Hero />
				<Bio />
				<Features />
				<Process />
				<Agencies />
				<Services />
				<Industries />
				<Models />
				<Footer />
			</main>
		</>
	);
}
